import React, { useState } from "react";

/**
 * ReportExport component
 * Usage:
 *   <ReportExport
 *      scores={{ legal, cyber }}
 *      riskStats={[{label, score, level}]}
 *      analysisSummary="..."
 *      userName="..."
 *   />
 *
 * Export and email actions are simulated; downloads produce CSV or minimal PDF (via SVG/HTML).
 *
 * Props:
 *   - scores: object
 *   - riskStats: array
 *   - analysisSummary: string
 *   - userName: string
 */
// PUBLIC_INTERFACE
function ReportExport({ scores = {}, riskStats = [], analysisSummary = "", userName = "" }) {
  const [showEmailModal, setShowEmailModal] = useState(false);
  const [emailAddress, setEmailAddress] = useState("");
  const [emailStatus, setEmailStatus] = useState(null);

  const handleExportCSV = () => {
    // Build CSV string
    const header = "Section,Value\n";
    let rows = [
      `User,${userName}`,
      `Legal Risk Score,${scores.legal}`,
      `Cyber Safety Score,${scores.cyber}`,
      `AI Summary,"${analysisSummary.replace(/"/g, '""')}"`
    ];
    riskStats.forEach(r =>
      rows.push(`Clause (${r.label}),${r.level} (${r.score})`)
    );
    const csv = header + rows.join("\n");
    const blob = new Blob([csv], {type: "text/csv"});
    const url = URL.createObjectURL(blob);
    // Download
    const a = document.createElement("a");
    a.href = url;
    a.download = "lexilock_report.csv";
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
    }, 100);
  };

  const handleExportPDF = () => {
    // Minimal PDF-experience: download as HTML-in-SVG, as client JS PDF gen not available.
    // (If real PDF library were present, use like jsPDF.)
    const html = `
      <html>
        <head>
          <meta charset="utf-8"><title>LexiLock Report</title>
        </head>
        <body>
          <h2>LexiLock Analysis Report</h2>
          <div><b>User:</b> ${userName}</div>
          <div><b>Legal Risk Score:</b> ${scores.legal}</div>
          <div><b>Cyber Safety Score:</b> ${scores.cyber}</div>
          <div><b>AI Summary:</b> ${analysisSummary}</div>
          <div><b>Clause Assessment:</b>
            <ul>
            ${riskStats.map(r => `<li>${r.label}: <b>${r.level}</b> (${r.score})</li>`).join("")}
            </ul>
          </div>
          <div style="margin-top:22px;font-size:11px;color:#888;">Generated by LexiLock [Demo]</div>
        </body>
      </html>
    `;
    const blob = new Blob([html], {type:"text/html"});
    // Download as .html file, simulate as "PDF"
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "lexilock_report.html";
    document.body.appendChild(a);
    a.click();
    setTimeout(() => {
      document.body.removeChild(a);
      URL.revokeObjectURL(a.href);
    }, 100);
  };

  const handleEmailSend = (e) => {
    e.preventDefault();
    setEmailStatus("sending");
    setTimeout(() => {
      setEmailStatus("sent");
      setTimeout(() => {
        setShowEmailModal(false);
        setEmailStatus(null);
        setEmailAddress("");
      }, 1300);
    }, 1200); // Simulate "sent"
  };

  return (
    <div style={{ display: "inline-flex", gap: 12, alignItems: "center" }}>
      <button className="btn" style={{ fontSize: 13 }} onClick={handleExportCSV}>
        Export CSV
      </button>
      <button className="btn" style={{ fontSize: 13 }} onClick={handleExportPDF}>
        Export PDF
      </button>
      <button className="btn" style={{ fontSize: 13 }} onClick={() => setShowEmailModal(true)}>
        Email Report
      </button>

      {showEmailModal && (
        <div
          style={{
            position: "fixed",
            left: 0, top: 0, width: "100vw", height: "100vh",
            background: "rgba(0,0,0,0.16)", zIndex: 999,
            display: "flex", alignItems: "center", justifyContent: "center"
          }}
        >
          <div style={{
            background: "var(--base-dark)",
            color: "var(--text-color)",
            borderRadius: 10,
            boxShadow: "0 2px 18px #0001",
            width: 330, maxWidth: "90vw",
            padding: 22,
            border: "2px solid var(--primary)"
          }}>
            <div style={{ fontWeight: 600, fontSize: 17, marginBottom: 8 }}>Send Report via Email</div>
            <form onSubmit={handleEmailSend}>
              <input
                autoFocus
                type="email"
                placeholder="Recipient email..."
                required
                value={emailAddress}
                style={{
                  width: "99%",
                  padding: "7px 10px",
                  borderRadius: 6,
                  fontSize: 14,
                  marginBottom: 10,
                  border: "1px solid var(--border-color)"
                }}
                onChange={e => setEmailAddress(e.target.value)}
                disabled={emailStatus === "sending"}
              />
              <div style={{ display: "flex", gap: 10 }}>
                <button
                  className="btn"
                  type="submit"
                  disabled={emailStatus === "sending" || !emailAddress}
                  style={{ flex: 1 }}
                >
                  {emailStatus === "sending" ? "Sending..." : "Send"}
                </button>
                <button
                  className="btn"
                  type="button"
                  style={{ flex: 1 }}
                  onClick={() => setShowEmailModal(false)}
                  disabled={emailStatus === "sending"}
                >
                  Cancel
                </button>
              </div>
            </form>
            {emailStatus === "sent" && (
              <div style={{ marginTop: 10, color: "#7ae451", fontWeight: 500, fontSize: 14 }}>
                Report sent!
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
}

export default ReportExport;
